# GitHub Actions workflow for CI/CD to Azure App Service

name: Build, Migrate, and Deploy ASP.Net Core app to Azure Web App - inventory-api-25

on:
  push:
    branches:
      - master # <- SESUAIKAN: Ganti 'master' jika branch utama Anda bernama 'main' atau yang lain
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: inventory-api-25
  DOTNET_VERSION: '9.x' 
  STARTUP_PROJECT_PATH: ''
  CSPROJ_FILE_NAME: 'API-Manajemen-Barang.csproj' 
  PUBLISH_DIR: 'publish_output'

jobs:
  build:
    runs-on: windows-latest 
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.STARTUP_PROJECT_PATH }}${{ env.CSPROJ_FILE_NAME }}

      - name: Build with dotnet
        run: dotnet build ${{ env.STARTUP_PROJECT_PATH }}${{ env.CSPROJ_FILE_NAME }} --configuration Release --no-restore

      # --- Migrasi Database ---
      - name: Install dotnet ef tool
        run: dotnet tool install --global dotnet-ef --version 8.0.0 # <- SESUAIKAN: Versi EF Core Anda

      # Menambahkan lokasi instalasi global tools ke variabel lingkungan PATH untuk runner Windows
      - name: Add dotnet ef to PATH
        run: |
          $DOTNET_TOOLS_PATH = "$env:USERPROFILE\.dotnet\tools"
          Write-Host "Adding $DOTNET_TOOLS_PATH to PATH"
          echo "$DOTNET_TOOLS_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run database migrations
        run: |
          Write-Host "Running EF Core database migrations..."
          dotnet ef database update --connection-string "${{ secrets.DB_CONNECTION_STRING_MIGRATION }}" --startup-project ${{ env.STARTUP_PROJECT_PATH }}${{ env.CSPROJ_FILE_NAME }} --verbose
          Write-Host "Database migration completed."
        env:
          DB_CONNECTION_STRING_MIGRATION: ${{ secrets.DB_CONNECTION_STRING_MIGRATION }}

      - name: dotnet publish
        run: dotnet publish ${{ env.STARTUP_PROJECT_PATH }}${{ env.CSPROJ_FILE_NAME }} -c Release -o ${{ env.PUBLISH_DIR }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          # MODIFIKASI: Gunakan variabel PUBLISH_DIR yang sudah didefinisikan
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10E6013196124F9D84D8116F43637D70 }} 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_075DC16425BE4A8F8174D00F6387A65A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4C4309F722044089DBD6B046C18CA2B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .

      - name: Logout from Azure
        run: az logout
